#!/bin/bash
#
# Proxmox Repository Setup Script
# Setup Proxmox repositories and remove subscription nag
# Works for both Proxmox VE (PVE) and Proxmox Backup Server (PBS)
#
# DEPLOYMENT:
#   Device: intel-1250p-proxmox-host (192.168.1.40)
#   Path:   /root/sh/proxmox-setup-repos.sh
#
#   Device: intel-n6005-proxmox-host (192.168.1.41)
#   Path:   /root/sh/proxmox-setup-repos.sh
#
#   Device: pve-proxmox-backup-server-1250p-lxc (192.168.1.52)
#   Path:   /root/sh/proxmox-setup-repos.sh
#
#   Backup: ~/Documents/dev/sh/proxmox-setup-repos.sh (Windows)
#
# USAGE:
#   ./proxmox-setup-repos.sh [debian_version]
#   Example: ./proxmox-setup-repos.sh trixie

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }
print_header() { echo -e "${BLUE}=== $1 ===${NC}"; }

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "This script must be run as root"
    exit 1
fi

# Detect Debian version
DEBIAN_VERSION="${1:-}"
if [ -z "$DEBIAN_VERSION" ]; then
    if [ -f /etc/os-release ]; then
        DEBIAN_VERSION=$(grep VERSION_CODENAME /etc/os-release | cut -d= -f2)
        print_info "Auto-detected Debian version: $DEBIAN_VERSION"
    else
        DEBIAN_VERSION="bookworm"
        print_warn "Could not detect Debian version, defaulting to: $DEBIAN_VERSION"
    fi
fi

# Detect if PVE or PBS
PROXMOX_TYPE=""
if [ -f /usr/bin/pvesh ]; then
    PROXMOX_TYPE="pve"
    print_info "Detected: Proxmox Virtual Environment (PVE)"
elif [ -f /usr/bin/proxmox-backup-manager ]; then
    PROXMOX_TYPE="pbs"
    print_info "Detected: Proxmox Backup Server (PBS)"
else
    print_error "This doesn't appear to be a Proxmox VE or PBS system"
    exit 1
fi

echo ""
print_header "Step 1: Backup existing repository configuration"

# Backup existing sources
BACKUP_DIR="/root/repo-backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"
cp -r /etc/apt/sources.list.d "$BACKUP_DIR/"
cp /etc/apt/sources.list "$BACKUP_DIR/" 2>/dev/null || true
print_info "Backed up to: $BACKUP_DIR"

echo ""
print_header "Step 2: Remove enterprise repositories"

# Remove PVE enterprise repo
if [ -f /etc/apt/sources.list.d/pve-enterprise.list ]; then
    print_info "Disabling PVE enterprise repository..."
    mv /etc/apt/sources.list.d/pve-enterprise.list \
       /etc/apt/sources.list.d/pve-enterprise.list.disabled
fi

# Remove PBS enterprise repo
if [ -f /etc/apt/sources.list.d/pbs-enterprise.list ]; then
    print_info "Disabling PBS enterprise repository..."
    mv /etc/apt/sources.list.d/pbs-enterprise.list \
       /etc/apt/sources.list.d/pbs-enterprise.list.disabled
fi

# Remove Ceph enterprise repo if present
if [ -f /etc/apt/sources.list.d/ceph.list ]; then
    if grep -q "enterprise" /etc/apt/sources.list.d/ceph.list 2>/dev/null; then
        print_info "Disabling Ceph enterprise repository..."
        mv /etc/apt/sources.list.d/ceph.list \
           /etc/apt/sources.list.d/ceph.list.disabled
    fi
fi

echo ""
print_header "Step 3: Add no-subscription repositories"

# Add PVE no-subscription repo
if [ "$PROXMOX_TYPE" = "pve" ]; then
    PVE_REPO_FILE="/etc/apt/sources.list.d/pve-no-subscription.list"
    print_info "Adding PVE no-subscription repository for $DEBIAN_VERSION..."
    cat > "$PVE_REPO_FILE" <<EOF
# Proxmox VE No-Subscription Repository
# Generated by proxmox-setup-repos.sh on $(date)
deb http://download.proxmox.com/debian/pve $DEBIAN_VERSION pve-no-subscription
EOF
    print_info "Created: $PVE_REPO_FILE"
fi

# Add PBS no-subscription repo
if [ "$PROXMOX_TYPE" = "pbs" ]; then
    PBS_REPO_FILE="/etc/apt/sources.list.d/pbs-no-subscription.list"
    print_info "Adding PBS no-subscription repository for $DEBIAN_VERSION..."
    cat > "$PBS_REPO_FILE" <<EOF
# Proxmox Backup Server No-Subscription Repository
# Generated by proxmox-setup-repos.sh on $(date)
deb http://download.proxmox.com/debian/pbs $DEBIAN_VERSION pbs-no-subscription
EOF
    print_info "Created: $PBS_REPO_FILE"
fi

echo ""
print_header "Step 4: Remove subscription nag popup"

# Find and patch proxmoxlib.js
NAG_FILE="/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"

if [ -f "$NAG_FILE" ]; then
    # Backup original file
    if [ ! -f "${NAG_FILE}.backup" ]; then
        cp "$NAG_FILE" "${NAG_FILE}.backup"
        print_info "Backed up original file to ${NAG_FILE}.backup"
    fi

    # Check if already patched
    if grep -q "checked_command: function(orig_cmd) { return orig_cmd; }" "$NAG_FILE"; then
        print_warn "Subscription nag already removed"
    else
        print_info "Removing subscription nag popup..."

        # Patch the file
        sed -i.bak "s/data.status.toLowerCase() !== 'active'/false/g" "$NAG_FILE"
        sed -i "s/checked_command: function(orig_cmd) {/checked_command: function(orig_cmd) { return orig_cmd; \/\/ Modified by proxmox-setup-repos.sh\n\/\/ Original code:/g" "$NAG_FILE"

        print_info "Subscription nag removed"
        print_warn "Note: You may need to clear your browser cache or use Ctrl+F5"
    fi
else
    print_warn "Could not find proxmoxlib.js - nag removal skipped"
fi

echo ""
print_header "Step 5: Update package lists"

print_info "Running apt update..."
apt update

echo ""
print_header "Setup Complete!"
echo ""
print_info "Summary:"
echo "  - Proxmox Type: $PROXMOX_TYPE"
echo "  - Debian Version: $DEBIAN_VERSION"
echo "  - Enterprise repos: Disabled"
echo "  - No-subscription repos: Enabled"
echo "  - Subscription nag: Removed"
echo "  - Backup location: $BACKUP_DIR"
echo ""
print_info "You can now run 'apt upgrade' to update your system"
echo ""
print_warn "Remember to clear your browser cache or use Ctrl+F5 to see nag removal"
